/* eslint-disable */

// @ts-nocheck

// This file was automatically generated by @caffeinelabs/bindgen@0.1.0.
// You should NOT make any changes in this file as it will be overwritten.
// Additionally, you should also exclude this file from your linter and/or formatter to prevent it from being checked or modified.

import type { ActorMethod } from '@icp-sdk/core/agent';
import type { IDL } from '@icp-sdk/core/candid';
import type { Principal } from '@icp-sdk/core/principal';

export interface StudySession {
  'date' : string,
  'stopCount' : bigint,
  'studySeconds' : bigint,
  'breakSeconds' : bigint,
}
export interface Subject {
  'id' : string,
  'name' : string,
  'createdAt' : bigint,
}
export interface TodoItem {
  'id' : bigint,
  'createdAt' : bigint,
  'text' : string,
  'completed' : boolean,
}
export interface Topic {
  'id' : string,
  'createdAt' : bigint,
  'text' : string,
  'completed' : boolean,
  'subjectId' : string,
}
export interface UserProfile { 'name' : string }
export type UserRole = { 'admin' : null } |
  { 'user' : null } |
  { 'guest' : null };
export interface _SERVICE {
  '_initializeAccessControlWithSecret' : ActorMethod<[string], undefined>,
  'addSubject' : ActorMethod<[string], Subject>,
  'addTodo' : ActorMethod<
    [string],
    {
      'id' : bigint,
      'createdAt' : bigint,
      'text' : string,
      'completed' : boolean,
    }
  >,
  'addTopics' : ActorMethod<[string, Array<string>], Array<Topic>>,
  'assignCallerUserRole' : ActorMethod<[Principal, UserRole], undefined>,
  'deleteSubject' : ActorMethod<[string], boolean>,
  'deleteTodo' : ActorMethod<[bigint], boolean>,
  'deleteTopic' : ActorMethod<[string], boolean>,
  'ensureUser' : ActorMethod<[], undefined>,
  'getCallerUserProfile' : ActorMethod<[], [] | [UserProfile]>,
  'getCallerUserRole' : ActorMethod<[], UserRole>,
  'getDailySessions' : ActorMethod<[], Array<StudySession>>,
  'getSubjects' : ActorMethod<[], Array<Subject>>,
  'getTodos' : ActorMethod<[], Array<TodoItem>>,
  'getTopics' : ActorMethod<[], Array<Topic>>,
  'getUserProfile' : ActorMethod<[Principal], [] | [UserProfile]>,
  'isCallerAdmin' : ActorMethod<[], boolean>,
  'saveCallerUserProfile' : ActorMethod<[UserProfile], undefined>,
  'saveDailySession' : ActorMethod<[string, bigint, bigint, bigint], undefined>,
  'toggleTodo' : ActorMethod<[bigint], TodoItem>,
  'toggleTopic' : ActorMethod<[string], Topic>,
}
export declare const idlService: IDL.ServiceClass;
export declare const idlInitArgs: IDL.Type[];
export declare const idlFactory: IDL.InterfaceFactory;
export declare const init: (args: { IDL: typeof IDL }) => IDL.Type[];