/* eslint-disable */

// @ts-nocheck

// This file was automatically generated by @caffeinelabs/bindgen@0.1.0.
// You should NOT make any changes in this file as it will be overwritten.
// Additionally, you should also exclude this file from your linter and/or formatter to prevent it from being checked or modified.

import { IDL } from '@icp-sdk/core/candid';

export const StudySession = IDL.Record({
  'date' : IDL.Text,
  'stopCount' : IDL.Nat,
  'studySeconds' : IDL.Nat,
  'breakSeconds' : IDL.Nat,
});
export const TodoItem = IDL.Record({
  'id' : IDL.Nat,
  'createdAt' : IDL.Int,
  'text' : IDL.Text,
  'completed' : IDL.Bool,
});

export const idlService = IDL.Service({
  'addTodo' : IDL.Func(
      [IDL.Text],
      [
        IDL.Record({
          'id' : IDL.Nat,
          'createdAt' : IDL.Int,
          'text' : IDL.Text,
          'completed' : IDL.Bool,
        }),
      ],
      [],
    ),
  'deleteTodo' : IDL.Func([IDL.Nat], [IDL.Bool], []),
  'getDailySessions' : IDL.Func([], [IDL.Vec(StudySession)], ['query']),
  'getTodos' : IDL.Func([], [IDL.Vec(TodoItem)], ['query']),
  'saveDailySession' : IDL.Func([IDL.Text, IDL.Nat, IDL.Nat, IDL.Nat], [], []),
  'toggleTodo' : IDL.Func([IDL.Nat], [TodoItem], []),
});

export const idlInitArgs = [];

export const idlFactory = ({ IDL }) => {
  const StudySession = IDL.Record({
    'date' : IDL.Text,
    'stopCount' : IDL.Nat,
    'studySeconds' : IDL.Nat,
    'breakSeconds' : IDL.Nat,
  });
  const TodoItem = IDL.Record({
    'id' : IDL.Nat,
    'createdAt' : IDL.Int,
    'text' : IDL.Text,
    'completed' : IDL.Bool,
  });
  
  return IDL.Service({
    'addTodo' : IDL.Func(
        [IDL.Text],
        [
          IDL.Record({
            'id' : IDL.Nat,
            'createdAt' : IDL.Int,
            'text' : IDL.Text,
            'completed' : IDL.Bool,
          }),
        ],
        [],
      ),
    'deleteTodo' : IDL.Func([IDL.Nat], [IDL.Bool], []),
    'getDailySessions' : IDL.Func([], [IDL.Vec(StudySession)], ['query']),
    'getTodos' : IDL.Func([], [IDL.Vec(TodoItem)], ['query']),
    'saveDailySession' : IDL.Func(
        [IDL.Text, IDL.Nat, IDL.Nat, IDL.Nat],
        [],
        [],
      ),
    'toggleTodo' : IDL.Func([IDL.Nat], [TodoItem], []),
  });
};

export const init = ({ IDL }) => { return []; };